name: gestures
description: Custom Gesture Detector for Flutter. Empower your users with custom gestures.
version: 0.0.1
homepage: https://github.com/AndreBaltazar8/flutter_gestures

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
